on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build -i
      - uses: actions/upload-artifact@v2
        with:
          name: shared
          path: |
            shared/build/outputs/aar/
            shared/build/xcode-frameworks/
      - uses: actions/upload-artifact@v2
        with:
          name: Android
          path: androidApp/build/outputs/apk/
